#!/bin/bash -eu

measure-velocity() {
  file_size=$(cat $1 | wc -c)
  chunk=$(( file_size / 10 ))

  for (( i=1; i<11; i++ )); do 
    export size=$(( chunk * i ))
    export compressed_size=$( dd if=$1 bs=10 count=$i 2>/dev/null | gzip | wc -c )
    printf "size=%d, compression=%s\n" $size "$( perl -e 'print $ENV{compressed_size}/$ENV{size}' )"
  done
}

for file in "$@"; do
  printf "$file: "
  measure-velocity $file | tail -1
done
